/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package visiontesting;

import org.opencv.core.Core;
import org.opencv.core.Mat;
import org.opencv.videoio.VideoCapture;
import org.opencv.imgcodecs.Imgcodecs;

public class App {
    public String getGreeting() {
        return "Hello world, lolz.";
    }

    public static void main(String[] args) {
        System.loadLibrary(Core.NATIVE_LIBRARY_NAME);
        System.out.println(new App().getGreeting());
        boolean cameraActive = true;
        VideoCapture camera = new VideoCapture(0);
        Mat frame = new Mat();
        if (args.length != 0) {
            cameraActive = false;
            frame = Imgcodecs.imread(args[0]);
        }
        Imshow im = new Imshow("Video Preview");
        im.Window.setResizable(true);
        while (true) {
            if (cameraActive) {
                camera.read(frame);
            }
            im.showImage(frame);
        }
    }
}
